version: 0.2
env:
  secrets-manager:
    DOCKERHUB_USERNAME: "codebuild/dockerhub/credentials:username"
    DOCKERHUB_PASSWORD: "codebuild/dockerhub/credentials:password"

phases:
  pre_build:
    commands:
      - echo ""
      - echo ""
      - echo "+++++++++++++++++PRE_BUILD++++++++++++++++++++++++++++++++"
      - echo "Logging into Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo ""
      - echo ""
      - echo "+++++++++++++++++BUILD++++++++++++++++++++++++++++++++"
      - echo "CODEBUILD_SOURCE_VERSION: $CODEBUILD_SOURCE_VERSION"
      - BRANCH=$(echo $CODEBUILD_SOURCE_VERSION | sed 's|refs/heads/||')
      - echo "BRANCH: $BRANCH"
      - COMMIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "COMMIT_SHA: $COMMIT_SHA"
      - BUILD_NUM=${CODEBUILD_BUILD_NUMBER}
      - echo "BUILD_NUM: $BUILD_NUM"
      - IMAGE_TAG="${BRANCH}-v1.0-${BUILD_NUM}-${COMMIT_SHA}" 
      - echo "Building: arkb2023/abode-website:${IMAGE_TAG}"
      - docker build -t arkb2023/abode-website:${IMAGE_TAG} .
      - docker tag arkb2023/abode-website:${IMAGE_TAG} arkb2023/abode-website:latest
      
  post_build:
    commands:
      - echo ""
      - echo ""
      - echo "+++++++++++++++++POST BUILD++++++++++++++++++++++++++++++++"
      - echo "Pushing to Docker Hub..."
      # - echo "CODEBUILD_SOURCE_VERSION: $CODEBUILD_SOURCE_VERSION"
      # - BRANCH=$(echo $CODEBUILD_SOURCE_VERSION | sed 's|refs/heads/||')
      # - echo "BRANCH: $BRANCH"
      # - COMMIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      # - echo "COMMIT_SHA: $COMMIT_SHA"
      # - BUILD_NUM=${CODEBUILD_BUILD_NUMBER}
      # - echo "BUILD_NUM: $BUILD_NUM"
      # - IMAGE_TAG="${BRANCH}-v1.0-${BUILD_NUM}-${COMMIT_SHA}" 
      # - docker push arkb2023/abode-website:${IMAGE_TAG}
      # - docker push arkb2023/abode-website:latest
      # - echo "Push Complete"
      # - echo "Image: arkb2023/abode-website:${IMAGE_TAG}"
      # - echo "Branch: ${BRANCH}"
      # - echo "Commit: ${COMMIT_SHA}"
